[tools]

# Core dependencies
just = "1.40.0"
"ubi:ethereum-optimism/kurtosis-test" = "0.0.1"
"ubi:kurtosis-tech/kurtosis-cli-release-artifacts[exe=kurtosis]" = "1.4.4"
"yq" = "v4.44.3"

# lint
"pipx:ethereum-optimism/kurtosis-lint" = "v0.0.3"
