name: CI

on:
  pull_request:

concurrency:
  group: "tests-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  run_with_args:
    strategy:
      matrix:
        file_name:
          [
            "./network_params.yaml",
            "./.github/tests/rollup-boost-rbuilder.yaml"
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

      - name: Run Starlark
        run: kurtosis run ${{ github.workspace }} --args-file ${{ matrix.file_name }} --verbosity detailed

  # Make sure that `kurtosis run .` without an --args-file works fine (the defaults in input_parser.star are correct)
  run_without_args:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Run Starlark
        run: kurtosis run ${{ github.workspace }} --verbosity detailed

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

      - name: Kurtosis Lint
        run: kurtosis lint ${{ github.workspace }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11

      - name: Run kurtosis-test tests
        run: kurtosis-test .

